### ISSUE TITLE
Add support for OpenFaaS gateways using basic authentication

### ISSUE THREAD

**Issue by alexellis** [affix/sidekiq-connector#1]
Hi Keiran,

All OpenFaaS gateways now use basic authentication which means that for this to be useful for users, you'll need to add support. Fortunately the ground-work has been done in the new connector SDK.

A worked example exists in the GitHub repo. Please could you take a look? https://github.com/openfaas-incubator/connector-sdk 

Alex

**Comment by alexellis** [comment]
Ping @affix

**Comment by affix** [comment]
thanks @alexellis I'll take a look :)

**Comment by alexellis** [comment]
@affix I can't see the basic auth here in the YAML file?

https://github.com/affix/sidekiq-connector/blob/master/yaml/kubernetes/connector-dep.yml

Does it need to be finished off?
